/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Resume.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author vinay
 */

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    //defining object of class PersonalInformation
    private PersonalInformation personalInformation;
    
    //Variables declaration
    private String firstName;
    private String lastName;
    private String workExperience;
    private String affiliation;
    private String careerObjectiveStatement;
    private File file;
    private String phoneNumber;
    private String emailAddress;
    private String computerSkills;
    private String linkedInProfileLink;
    private String hobbies;
    private String month;
    private String date;
    private String year;
    private String street1;    
    private String street2;
    private String city;
    private String country;
    private String zipCode;
    private String degree1Title;
    private String degree1Date;
    private String university1;
    private String degree2Title;
    private String degree2Date;
    private String university2;
    private String degree3Title;
    private String degree3Date;
    private String university3;
    private String imageURL;
    private Boolean checkValidity = false;
    private File f;
    
    public CreateJPanel(PersonalInformation personalInformation) {
        initComponents();
        this.personalInformation = personalInformation;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        createResumeTitleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        emailAddressLabel1 = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        linkedInProfileLinkLabel = new javax.swing.JLabel();
        educationHistoryLabel = new javax.swing.JLabel();
        degree1TitleLabel = new javax.swing.JLabel();
        degree1DateLabel = new javax.swing.JLabel();
        university1Name = new javax.swing.JLabel();
        careerObjectiveLabel = new javax.swing.JLabel();
        streetName1Label = new javax.swing.JLabel();
        streetName2Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        degree1Label = new javax.swing.JLabel();
        degree2TitleLabel = new javax.swing.JLabel();
        degree2DateLabel = new javax.swing.JLabel();
        university2Name = new javax.swing.JLabel();
        degree1Label1 = new javax.swing.JLabel();
        degree3TitleLabel = new javax.swing.JLabel();
        degree3DateLabel = new javax.swing.JLabel();
        university3Name = new javax.swing.JLabel();
        degree3Label = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        addressInformationLabel1 = new javax.swing.JLabel();
        createResumeButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        imageURLTextField = new javax.swing.JTextField();
        imageAttachButton = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailAddressTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        computerSkillsTextField = new javax.swing.JTextField();
        linkedINProfileLinkTextField = new javax.swing.JTextField();
        degreeTitle1TextField = new javax.swing.JTextField();
        degree1DateTextField = new javax.swing.JTextField();
        university1TextField = new javax.swing.JTextField();
        degreeTitle2TextField = new javax.swing.JTextField();
        degree2DateTextField = new javax.swing.JTextField();
        university2TextField = new javax.swing.JTextField();
        degreeTitle3TextField = new javax.swing.JTextField();
        degree3DateTextField = new javax.swing.JTextField();
        university3TextField = new javax.swing.JTextField();
        workExperienceTextArea = new java.awt.TextArea();
        hobbiesLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        workExperienceLabel = new javax.swing.JLabel();
        careerObjectiveTextArea = new java.awt.TextArea();
        streetname1TextField = new javax.swing.JTextField();
        streetname2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        hobbiesTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        createResumeTitleLabel.setFont(new java.awt.Font("Verdana", 2, 36)); // NOI18N
        createResumeTitleLabel.setText("Create your Resume");

        firstNameLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        firstNameLabel.setText("First Name*:");

        lastNameLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lastNameLabel.setText("Last Name*:");

        emailAddressLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        emailAddressLabel.setText("Email Address*:");

        emailAddressLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        emailAddressLabel1.setText("Birth Information");

        monthLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        monthLabel.setText("Month(1-12)*:");

        dateLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        dateLabel.setText("Date*:");

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        yearLabel.setText("Year*:");

        phoneNumberLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        phoneNumberLabel.setText("Phone number(cell)*:");

        phoneNumberLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        phoneNumberLabel1.setText("Computer Skills known*:");

        linkedInProfileLinkLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        linkedInProfileLinkLabel.setText("LinkedIn Profile Link*:");

        educationHistoryLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        educationHistoryLabel.setText("Education History");

        degree1TitleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree1TitleLabel.setText("Degree earned(Degree Title):");

        degree1DateLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree1DateLabel.setText("Degree issuance date (Month/Year):");

        university1Name.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university1Name.setText("University Name :");

        careerObjectiveLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        careerObjectiveLabel.setText("Career Objective*:");

        streetName1Label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        streetName1Label.setText("Address Street Name 1*:");

        streetName2Label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        streetName2Label.setText("Street Name 2*:");

        cityLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        cityLabel.setText("City*:");

        countryLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        countryLabel.setText("Country*:");

        zipCodeLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        zipCodeLabel.setText("Zip Code*:");

        degree1Label.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        degree1Label.setText("Degree 1*:");

        degree2TitleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree2TitleLabel.setText("Degree earned(Degree Title):");

        degree2DateLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree2DateLabel.setText("Degree issuance date (Month/Year):");

        university2Name.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university2Name.setText("University Name :");

        degree1Label1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        degree1Label1.setText("Degree 2:");

        degree3TitleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree3TitleLabel.setText("Degree earned(Degree Title):");

        degree3DateLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree3DateLabel.setText("Degree issuance date (Month/Year):");

        university3Name.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university3Name.setText("University Name :");

        degree3Label.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        degree3Label.setText("Degree 3:");

        hobbiesLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        hobbiesLabel.setText("Hobbies:");

        addressInformationLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        addressInformationLabel1.setText("Upload Image*");

        createResumeButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        createResumeButton.setText("Create Resume");
        createResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResumeButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        resetButton.setText("Reset/Clear");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        imageURLTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        imageAttachButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        imageAttachButton.setText("Attach file");
        imageAttachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageAttachButtonActionPerformed(evt);
            }
        });

        firstNameTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        emailAddressTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        emailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressTextFieldActionPerformed(evt);
            }
        });

        monthTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });

        dateTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        yearTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        phoneNumberTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        computerSkillsTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        computerSkillsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerSkillsTextFieldActionPerformed(evt);
            }
        });

        linkedINProfileLinkTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        linkedINProfileLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedINProfileLinkTextFieldActionPerformed(evt);
            }
        });

        degreeTitle1TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degreeTitle1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle1TextFieldActionPerformed(evt);
            }
        });

        degree1DateTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree1DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree1DateTextFieldActionPerformed(evt);
            }
        });

        university1TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university1TextFieldActionPerformed(evt);
            }
        });

        degreeTitle2TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degreeTitle2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle2TextFieldActionPerformed(evt);
            }
        });

        degree2DateTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree2DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree2DateTextFieldActionPerformed(evt);
            }
        });

        university2TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university2TextFieldActionPerformed(evt);
            }
        });

        degreeTitle3TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degreeTitle3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle3TextFieldActionPerformed(evt);
            }
        });

        degree3DateTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        degree3DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree3DateTextFieldActionPerformed(evt);
            }
        });

        university3TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        university3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university3TextFieldActionPerformed(evt);
            }
        });

        workExperienceTextArea.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        hobbiesLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        hobbiesLabel1.setText("Affiliations*:");

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Fields marked with * are mandatory");

        workExperienceLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        workExperienceLabel.setText("Work Experience*:");

        careerObjectiveTextArea.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        streetname1TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        streetname1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetname1TextFieldActionPerformed(evt);
            }
        });

        streetname2TextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        streetname2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetname2TextFieldActionPerformed(evt);
            }
        });

        cityTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });

        countryTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });

        zipCodeTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeTextFieldActionPerformed(evt);
            }
        });

        hobbiesTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        hobbiesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobbiesTextFieldActionPerformed(evt);
            }
        });

        affiliationTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        affiliationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affiliationTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameLabel)
                                .addComponent(emailAddressLabel)
                                .addComponent(dateLabel)
                                .addComponent(yearLabel)
                                .addComponent(phoneNumberLabel)
                                .addComponent(phoneNumberLabel1)
                                .addComponent(linkedInProfileLinkLabel)
                                .addComponent(degree1TitleLabel)
                                .addComponent(degree1DateLabel)
                                .addComponent(university1Name)
                                .addComponent(degree2TitleLabel)
                                .addComponent(degree2DateLabel)
                                .addComponent(university2Name)
                                .addComponent(degree3TitleLabel)
                                .addComponent(degree3DateLabel)
                                .addComponent(university3Name)
                                .addComponent(careerObjectiveLabel)
                                .addComponent(streetName1Label)
                                .addComponent(streetName2Label)
                                .addComponent(cityLabel)
                                .addComponent(countryLabel)
                                .addComponent(zipCodeLabel)
                                .addComponent(hobbiesLabel))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(monthLabel)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(educationHistoryLabel)
                                        .addComponent(emailAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createResumeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree1Label)
                            .addComponent(degree1Label1)
                            .addComponent(degree3Label)
                            .addComponent(hobbiesLabel1))
                        .addGap(766, 766, 766)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workExperienceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAttachButton)
                    .addComponent(careerObjectiveTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(university3TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(degree3DateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(degreeTitle3TextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(university2TextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(degree2DateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(degreeTitle2TextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(university1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(degree1DateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(degreeTitle1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(linkedINProfileLinkTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(computerSkillsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(yearTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(monthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailAddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(streetname1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetname2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(createResumeButton)
                        .addGap(83, 83, 83)
                        .addComponent(resetButton))
                    .addComponent(imageURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInformationLabel1)
                    .addComponent(jLabel1)
                    .addComponent(workExperienceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(firstNameLabel)
                    .addContainerGap(1131, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createResumeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(37, 37, 37)
                                                        .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(dateLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(yearLabel))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(computerSkillsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(phoneNumberLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emailAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(linkedINProfileLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(linkedInProfileLinkLabel))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(educationHistoryLabel)
                                        .addGap(8, 8, 8)
                                        .addComponent(degree1Label)
                                        .addGap(0, 0, 0)
                                        .addComponent(degree1TitleLabel))
                                    .addComponent(degreeTitle1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degree1DateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(degree1DateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(university1Name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(university1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degree1Label1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(university2Name)
                                            .addComponent(university2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(degreeTitle2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(degree2TitleLabel))
                                                .addGap(28, 28, 28)
                                                .addComponent(degree2DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(degree2DateLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(12, 12, 12)
                                .addComponent(degree3Label)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(degreeTitle3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(degree3TitleLabel))
                                                .addGap(18, 18, 18)
                                                .addComponent(degree3DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(degree3DateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(university3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(university3Name))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(careerObjectiveTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(careerObjectiveLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(workExperienceLabel)
                                                            .addComponent(workExperienceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(109, 109, 109)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(streetName1Label)
                                                            .addComponent(streetname1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(streetname2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(streetName2Label, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(16, 16, 16)
                                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cityLabel))
                                        .addGap(22, 22, 22)
                                        .addComponent(countryLabel))
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(zipCodeLabel))
                        .addGap(23, 23, 23)
                        .addComponent(hobbiesLabel)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hobbiesLabel1)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(addressInformationLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAttachButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(createResumeButton)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2293, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
   
    private void createResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResumeButtonActionPerformed
        // Method to collect all the deta from the user input.
        fetchData();
        
        //Validation of Data which the user has provided.
       checkValidity = validateData();
        
        if(checkValidity){
         
            //If the validation is correct, then set the information provided by the user in the desired field.
            setData();
            JOptionPane.showMessageDialog(null,"All the information was recorded successfully", "Congratulations", 1);
            resetButtonActionPerformed(evt);
        }
       
    }//GEN-LAST:event_createResumeButtonActionPerformed

    private void fetchData(){
        
    //fetch all the data into local variables    
     firstName = firstNameTextField.getText();
     lastName = lastNameTextField.getText();
     affiliation = affiliationTextField.getText();
     careerObjectiveStatement = careerObjectiveTextArea.getText();
     phoneNumber = phoneNumberTextField.getText();
     emailAddress = emailAddressTextField.getText();
     computerSkills = computerSkillsTextField.getText();
     linkedInProfileLink = linkedINProfileLinkTextField.getText();
     hobbies = hobbiesTextField.getText();
     month = monthTextField.getText();
     date = dateTextField.getText();
     year = yearTextField.getText();
     street1 = streetname1TextField.getText();
     street2 = streetname2TextField.getText();
     city = cityTextField.getText();
     country = countryTextField.getText();
     zipCode = zipCodeTextField.getText();
     degree1Title = degreeTitle1TextField.getText();
     degree1Date = degree1DateTextField.getText();
     university1 = university1TextField.getText();
     degree2Title = degreeTitle2TextField.getText();
     degree2Date = degree2DateTextField.getText();
     university2 = university2TextField.getText();
     degree3Title = degreeTitle3TextField.getText();
     degree3Date = degree3DateTextField.getText();
     university3 = university3TextField.getText();
     imageURL =  imageURLTextField.getText();
     workExperience = workExperienceTextArea.getText();
        
    }
    
    private boolean validateData(){
        
        //checking the validity of the user input.
        //1. All the mandatory fields have been filled or not.
        //2. Validating Email id, Telephone number, date of birth, zip code

        if(university1.isEmpty() || degree1Date.isEmpty() || workExperience.isEmpty()|| imageURL.isEmpty() || degree1Title.isEmpty() || zipCode.isEmpty() || country.isEmpty() || city.isEmpty() || street2.isEmpty() || street1.isEmpty() || year.isEmpty() || date.isEmpty() || month.isEmpty() || linkedInProfileLink.isEmpty() || computerSkills.isEmpty() || emailAddress.isEmpty() || phoneNumber.isEmpty()|| careerObjectiveStatement.isEmpty() || affiliation.isEmpty() || lastName.isEmpty() || firstName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all Mandatory fields", "Fields Empty!", 1);
            return false;
        }
         else if(!emailAddress.contains("@") || !emailAddress.contains(".") || emailAddress.contains(" ")){
                JOptionPane.showMessageDialog(null, "Invalid Email Address", "Invalid Input!", 2); return false;}
            else if(!month.matches("[0-9]+")&& month.length()>2 || !year.matches("[0-9]+") && year.length() > 4 || !date.matches("[0-9]+")&& date.length()>2){    
                JOptionPane.showMessageDialog(null, "Birth details are incorrect", "Birth information incorrect!", 2); return false;}
            else if(!zipCode.matches("[0-9]+")){
                JOptionPane.showMessageDialog(null, "Zip Code incorrect", "Incorrect Information!", 2); return false;}
            else if(!phoneNumber.matches("[0-9]+")){
                JOptionPane.showMessageDialog(null, "Phone number incorrect", "Incorrect Information!", 2);  return false;}

        return true;
    }
    
    private void setData(){
        
        personalInformation.address.setStreet1(street1);
        personalInformation.address.setStreet2(street2);
        personalInformation.address.setCity(city);
        personalInformation.address.setCountry(country);
        personalInformation.address.setZipCode(zipCode);
        
        personalInformation.education.setDegree1Title(degree1Title);
        personalInformation.education.setDegree2Title(degree2Title);
        personalInformation.education.setDegree3Title(degree3Title);
        personalInformation.education.setDegree1Date(degree1Date);
        personalInformation.education.setDegree2Date(degree2Date);
        personalInformation.education.setDegree3Date(degree2Date);
        personalInformation.education.setUniversity1(university1);
        personalInformation.education.setUniversity2(university2);
        personalInformation.education.setUniversity3(university3);
        
        personalInformation.setFirstName(firstName);
        personalInformation.setLastName(lastName);
        personalInformation.setEmailAddress(emailAddress);
        personalInformation.setMonth(month);
        personalInformation.setDate(date);
        personalInformation.setYear(year);
        personalInformation.setLinkedInProfileLink(linkedInProfileLink);
        personalInformation.setCareerObjectiveStatement(careerObjectiveStatement);
        personalInformation.setPhoneNumber(phoneNumber);
        personalInformation.setHobbies(hobbies);
        personalInformation.setAffiliation(affiliation);
        personalInformation.setFile(f);
        personalInformation.setWorkExperience(workExperience);
        personalInformation.setComputerSkills(computerSkills);
        
        
        
        
        
    }
               
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        
       
         firstNameTextField.setText("");
         lastNameTextField.setText("");
         affiliationTextField.setText("");
         careerObjectiveTextArea.setText("");
         phoneNumberTextField.setText("");
         emailAddressTextField.setText("");
         computerSkillsTextField.setText("");
         linkedINProfileLinkTextField.setText("");
         hobbiesTextField.setText("");
         monthTextField.setText("");
         dateTextField.setText("");
         yearTextField.setText("");
         streetname1TextField.setText("");
         streetname2TextField.setText("");
         cityTextField.setText("");
         countryTextField.setText("");
         zipCodeTextField.setText("");
         degreeTitle1TextField.setText("");
         degree1DateTextField.setText("");
         university1TextField.setText("");
         degreeTitle2TextField.setText("");
         degree2DateTextField.setText("");
         university2TextField.setText("");
         degreeTitle3TextField.setText("");
         degree3DateTextField.setText("");
         university3TextField.setText("");
         imageURLTextField.setText("");
         workExperienceTextArea.setText("");

    }//GEN-LAST:event_resetButtonActionPerformed

    
    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void emailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void linkedINProfileLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedINProfileLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkedINProfileLinkTextFieldActionPerformed

    private void degreeTitle1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle1TextFieldActionPerformed

    private void degree1DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree1DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree1DateTextFieldActionPerformed

    private void university1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university1TextFieldActionPerformed

    private void degreeTitle2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle2TextFieldActionPerformed

    private void degree2DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree2DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree2DateTextFieldActionPerformed

    private void university2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university2TextFieldActionPerformed

    private void degreeTitle3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle3TextFieldActionPerformed

    private void degree3DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree3DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree3DateTextFieldActionPerformed

    private void university3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university3TextFieldActionPerformed

    private void imageAttachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageAttachButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        f =jFileChooser.getSelectedFile();
        String fileName=f.getAbsolutePath();
        imageURLTextField.setText(fileName);
    }//GEN-LAST:event_imageAttachButtonActionPerformed

    private void computerSkillsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerSkillsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerSkillsTextFieldActionPerformed

    private void streetname1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetname1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetname1TextFieldActionPerformed

    private void streetname2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetname2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetname2TextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void hobbiesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobbiesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hobbiesTextFieldActionPerformed

    private void affiliationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiliationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affiliationTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressInformationLabel1;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel careerObjectiveLabel;
    private java.awt.TextArea careerObjectiveTextArea;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField computerSkillsTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createResumeButton;
    private javax.swing.JLabel createResumeTitleLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel degree1DateLabel;
    private javax.swing.JTextField degree1DateTextField;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JLabel degree1Label1;
    private javax.swing.JLabel degree1TitleLabel;
    private javax.swing.JLabel degree2DateLabel;
    private javax.swing.JTextField degree2DateTextField;
    private javax.swing.JLabel degree2TitleLabel;
    private javax.swing.JLabel degree3DateLabel;
    private javax.swing.JTextField degree3DateTextField;
    private javax.swing.JLabel degree3Label;
    private javax.swing.JLabel degree3TitleLabel;
    private javax.swing.JTextField degreeTitle1TextField;
    private javax.swing.JTextField degreeTitle2TextField;
    private javax.swing.JTextField degreeTitle3TextField;
    private javax.swing.JLabel educationHistoryLabel;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel emailAddressLabel1;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JLabel hobbiesLabel1;
    private javax.swing.JTextField hobbiesTextField;
    private javax.swing.JButton imageAttachButton;
    private javax.swing.JTextField imageURLTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField linkedINProfileLinkTextField;
    private javax.swing.JLabel linkedInProfileLinkLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel streetName1Label;
    private javax.swing.JLabel streetName2Label;
    private javax.swing.JTextField streetname1TextField;
    private javax.swing.JTextField streetname2TextField;
    private javax.swing.JLabel university1Name;
    private javax.swing.JTextField university1TextField;
    private javax.swing.JLabel university2Name;
    private javax.swing.JTextField university2TextField;
    private javax.swing.JLabel university3Name;
    private javax.swing.JTextField university3TextField;
    private javax.swing.JLabel workExperienceLabel;
    private java.awt.TextArea workExperienceTextArea;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
