/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author vinay
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    public DisplayJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        emailAddressLabel1 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        createResumeTitleLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        linkedInProfileLinkLabel = new javax.swing.JLabel();
        educationHistoryLabel = new javax.swing.JLabel();
        degreeTitleLabel = new javax.swing.JLabel();
        degreeDateLabel = new javax.swing.JLabel();
        universityName = new javax.swing.JLabel();
        careerObjectiveLabel = new javax.swing.JLabel();
        addressInformationLabel = new javax.swing.JLabel();

        setLayout(null);

        emailAddressLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailAddressLabel1.setText("Birth Information");

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");

        monthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthLabel.setText("Month:");

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setText("Date:");

        createResumeTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createResumeTitleLabel.setText("Create your Resume");

        emailAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailAddressLabel.setText("Email Address:");

        yearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearLabel.setText("Year:");

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberLabel.setText("Phone number(cell):");

        phoneNumberLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberLabel1.setText("Computer Skills known:");

        linkedInProfileLinkLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkedInProfileLinkLabel.setText("LinkedIn Profile Link:");

        educationHistoryLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        educationHistoryLabel.setText("Education History");

        degreeTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degreeTitleLabel.setText("Latest Degree earned(Degree Title):");

        degreeDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degreeDateLabel.setText("Degree issuance date (Month/Year):");

        universityName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        universityName.setText("University Name :");

        careerObjectiveLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        careerObjectiveLabel.setText("Career Objective:");

        addressInformationLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressInformationLabel.setText("Address Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(createResumeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(emailAddressLabel)
                            .addComponent(emailAddressLabel1)
                            .addComponent(monthLabel)
                            .addComponent(dateLabel)
                            .addComponent(yearLabel)
                            .addComponent(phoneNumberLabel)
                            .addComponent(phoneNumberLabel1)
                            .addComponent(linkedInProfileLinkLabel)
                            .addComponent(educationHistoryLabel)
                            .addComponent(degreeTitleLabel)
                            .addComponent(degreeDateLabel)
                            .addComponent(universityName)
                            .addComponent(careerObjectiveLabel)
                            .addComponent(addressInformationLabel))))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(createResumeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearLabel)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumberLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linkedInProfileLinkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(educationHistoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(degreeTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(degreeDateLabel)
                .addGap(21, 21, 21)
                .addComponent(universityName)
                .addGap(18, 18, 18)
                .addComponent(careerObjectiveLabel)
                .addGap(18, 18, 18)
                .addComponent(addressInformationLabel)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 928, 778);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressInformationLabel;
    private javax.swing.JLabel careerObjectiveLabel;
    private javax.swing.JLabel createResumeTitleLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel degreeDateLabel;
    private javax.swing.JLabel degreeTitleLabel;
    private javax.swing.JLabel educationHistoryLabel;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel emailAddressLabel1;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel linkedInProfileLinkLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JLabel universityName;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
