/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author vinay
 */
public class Timepass extends javax.swing.JPanel {

    /**
     * Creates new form Timepass
     */
    public Timepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createResumeTitleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        emailAddressLabel1 = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        linkedInProfileLinkLabel = new javax.swing.JLabel();
        educationHistoryLabel = new javax.swing.JLabel();
        degree1TitleLabel = new javax.swing.JLabel();
        degree1DateLabel = new javax.swing.JLabel();
        university1Name = new javax.swing.JLabel();
        careerObjectiveLabel = new javax.swing.JLabel();
        addressInformationLabel = new javax.swing.JLabel();
        streetName1Label = new javax.swing.JLabel();
        streetName2Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        degree1Label = new javax.swing.JLabel();
        degree2TitleLabel = new javax.swing.JLabel();
        degree2DateLabel = new javax.swing.JLabel();
        university2Name = new javax.swing.JLabel();
        degree1Label1 = new javax.swing.JLabel();
        degree3TitleLabel = new javax.swing.JLabel();
        degree3DateLabel = new javax.swing.JLabel();
        university3Name = new javax.swing.JLabel();
        degree3Label = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        addressInformationLabel1 = new javax.swing.JLabel();
        createResumeButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        imageURLTextField = new javax.swing.JTextField();
        imageAttachButton = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailAddressTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        computerSkillsTextField = new javax.swing.JTextField();
        linkedINProfileLinkTextField = new javax.swing.JTextField();
        degreeTitle1TextField = new javax.swing.JTextField();
        degree1DateTextField = new javax.swing.JTextField();
        university1TextField = new javax.swing.JTextField();
        degreeTitle2TextField = new javax.swing.JTextField();
        degree2DateTextField = new javax.swing.JTextField();
        university2TextField = new javax.swing.JTextField();
        degreeTitle3TextField = new javax.swing.JTextField();
        degree3DateTextField = new javax.swing.JTextField();
        university3TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        streetname2TextField = new javax.swing.JTextField();
        streetname1TextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        firstNameTextField23 = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();

        setLayout(null);

        createResumeTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createResumeTitleLabel.setText("Create your Resume");
        add(createResumeTitleLabel);
        createResumeTitleLabel.setBounds(355, 46, 231, 36);

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");
        add(firstNameLabel);
        firstNameLabel.setBounds(119, 115, 90, 32);

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");
        add(lastNameLabel);
        lastNameLabel.setBounds(119, 156, 89, 32);

        emailAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailAddressLabel.setText("Email Address:");
        add(emailAddressLabel);
        emailAddressLabel.setBounds(119, 197, 116, 32);

        emailAddressLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailAddressLabel1.setText("Birth Information");
        add(emailAddressLabel1);
        emailAddressLabel1.setBounds(119, 238, 159, 32);

        monthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthLabel.setText("Month:");
        add(monthLabel);
        monthLabel.setBounds(119, 279, 56, 32);

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setText("Date:");
        add(dateLabel);
        dateLabel.setBounds(119, 323, 42, 22);

        yearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearLabel.setText("Year:");
        add(yearLabel);
        yearLabel.setBounds(119, 367, 40, 22);

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberLabel.setText("Phone number(cell):");
        add(phoneNumberLabel);
        phoneNumberLabel.setBounds(119, 413, 160, 22);

        phoneNumberLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberLabel1.setText("Computer Skills known:");
        add(phoneNumberLabel1);
        phoneNumberLabel1.setBounds(119, 457, 186, 22);

        linkedInProfileLinkLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkedInProfileLinkLabel.setText("LinkedIn Profile Link:");
        add(linkedInProfileLinkLabel);
        linkedInProfileLinkLabel.setBounds(119, 501, 167, 22);

        educationHistoryLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        educationHistoryLabel.setText("Education History");
        add(educationHistoryLabel);
        educationHistoryLabel.setBounds(119, 544, 159, 22);

        degree1TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree1TitleLabel.setText("Degree earned(Degree Title):");
        add(degree1TitleLabel);
        degree1TitleLabel.setBounds(119, 623, 229, 22);

        degree1DateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree1DateLabel.setText("Degree issuance date (Month/Year):");
        add(degree1DateLabel);
        degree1DateLabel.setBounds(119, 669, 284, 22);

        university1Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university1Name.setText("University Name :");
        add(university1Name);
        university1Name.setBounds(119, 715, 140, 22);

        careerObjectiveLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        careerObjectiveLabel.setText("Career Objective:");
        add(careerObjectiveLabel);
        careerObjectiveLabel.setBounds(119, 1105, 135, 22);

        addressInformationLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressInformationLabel.setText("Address Information");
        add(addressInformationLabel);
        addressInformationLabel.setBounds(119, 1201, 186, 22);

        streetName1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetName1Label.setText("Street Name 1:");
        add(streetName1Label);
        streetName1Label.setBounds(119, 1239, 119, 22);

        streetName2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetName2Label.setText("Street Name 2:");
        add(streetName2Label);
        streetName2Label.setBounds(119, 1277, 119, 22);

        cityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cityLabel.setText("City:");
        add(cityLabel);
        cityLabel.setBounds(119, 1315, 36, 22);

        countryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countryLabel.setText("Country:");
        add(countryLabel);
        countryLabel.setBounds(119, 1353, 68, 22);

        zipCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zipCodeLabel.setText("Zip Code:");
        add(zipCodeLabel);
        zipCodeLabel.setBounds(119, 1394, 76, 22);

        degree1Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        degree1Label.setText("Degree 1:");
        add(degree1Label);
        degree1Label.setBounds(119, 582, 89, 22);

        degree2TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree2TitleLabel.setText("Degree earned(Degree Title):");
        add(degree2TitleLabel);
        degree2TitleLabel.setBounds(119, 799, 229, 22);

        degree2DateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree2DateLabel.setText("Degree issuance date (Month/Year):");
        add(degree2DateLabel);
        degree2DateLabel.setBounds(119, 845, 284, 22);

        university2Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university2Name.setText("University Name :");
        add(university2Name);
        university2Name.setBounds(119, 891, 140, 22);

        degree1Label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        degree1Label1.setText("Degree 2:");
        add(degree1Label1);
        degree1Label1.setBounds(119, 758, 89, 22);

        degree3TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree3TitleLabel.setText("Degree earned(Degree Title):");
        add(degree3TitleLabel);
        degree3TitleLabel.setBounds(119, 972, 229, 22);

        degree3DateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree3DateLabel.setText("Degree issuance date (Month/Year):");
        add(degree3DateLabel);
        degree3DateLabel.setBounds(119, 1012, 284, 22);

        university3Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university3Name.setText("University Name :");
        add(university3Name);
        university3Name.setBounds(119, 1052, 140, 22);

        degree3Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        degree3Label.setText("Degree 3:");
        add(degree3Label);
        degree3Label.setBounds(119, 934, 89, 22);

        hobbiesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hobbiesLabel.setText("Hobbies:");
        add(hobbiesLabel);
        hobbiesLabel.setBounds(119, 1440, 69, 22);

        addressInformationLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressInformationLabel1.setText("Upload Image");
        add(addressInformationLabel1);
        addressInformationLabel1.setBounds(119, 1483, 126, 22);

        createResumeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createResumeButton.setText("Create Resume");
        createResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResumeButtonActionPerformed(evt);
            }
        });
        add(createResumeButton);
        createResumeButton.setBounds(208, 1559, 195, 37);

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetButton.setText("Reset/Clear");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(421, 1559, 155, 37);
        add(imageURLTextField);
        imageURLTextField.setBounds(119, 1522, 376, 26);

        imageAttachButton.setText("Attach file");
        add(imageAttachButton);
        imageAttachButton.setBounds(510, 1521, 103, 29);

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        add(firstNameTextField);
        firstNameTextField.setBounds(494, 117, 119, 28);

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        add(lastNameTextField);
        lastNameTextField.setBounds(494, 158, 119, 28);

        emailAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressTextFieldActionPerformed(evt);
            }
        });
        add(emailAddressTextField);
        emailAddressTextField.setBounds(494, 199, 119, 28);

        monthTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        add(monthTextField);
        monthTextField.setBounds(494, 281, 119, 28);

        dateTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        add(dateTextField);
        dateTextField.setBounds(494, 320, 119, 28);

        yearTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        add(yearTextField);
        yearTextField.setBounds(494, 364, 119, 28);

        phoneNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        add(phoneNumberTextField);
        phoneNumberTextField.setBounds(494, 410, 119, 28);

        computerSkillsTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        computerSkillsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerSkillsTextFieldActionPerformed(evt);
            }
        });
        add(computerSkillsTextField);
        computerSkillsTextField.setBounds(494, 454, 119, 28);

        linkedINProfileLinkTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkedINProfileLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedINProfileLinkTextFieldActionPerformed(evt);
            }
        });
        add(linkedINProfileLinkTextField);
        linkedINProfileLinkTextField.setBounds(494, 498, 119, 28);

        degreeTitle1TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degreeTitle1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle1TextFieldActionPerformed(evt);
            }
        });
        add(degreeTitle1TextField);
        degreeTitle1TextField.setBounds(494, 620, 119, 28);

        degree1DateTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree1DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree1DateTextFieldActionPerformed(evt);
            }
        });
        add(degree1DateTextField);
        degree1DateTextField.setBounds(494, 666, 119, 28);

        university1TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university1TextFieldActionPerformed(evt);
            }
        });
        add(university1TextField);
        university1TextField.setBounds(494, 712, 119, 28);

        degreeTitle2TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degreeTitle2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle2TextFieldActionPerformed(evt);
            }
        });
        add(degreeTitle2TextField);
        degreeTitle2TextField.setBounds(494, 796, 119, 28);

        degree2DateTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree2DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree2DateTextFieldActionPerformed(evt);
            }
        });
        add(degree2DateTextField);
        degree2DateTextField.setBounds(494, 842, 119, 28);

        university2TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university2TextFieldActionPerformed(evt);
            }
        });
        add(university2TextField);
        university2TextField.setBounds(494, 888, 119, 28);

        degreeTitle3TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degreeTitle3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTitle3TextFieldActionPerformed(evt);
            }
        });
        add(degreeTitle3TextField);
        degreeTitle3TextField.setBounds(494, 954, 119, 28);

        degree3DateTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        degree3DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree3DateTextFieldActionPerformed(evt);
            }
        });
        add(degree3DateTextField);
        degree3DateTextField.setBounds(494, 1000, 119, 28);

        university3TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        university3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university3TextFieldActionPerformed(evt);
            }
        });
        add(university3TextField);
        university3TextField.setBounds(494, 1046, 119, 28);

        cityTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });
        add(cityTextField);
        cityTextField.setBounds(494, 1309, 119, 28);

        streetname2TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetname2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetname2TextFieldActionPerformed(evt);
            }
        });
        add(streetname2TextField);
        streetname2TextField.setBounds(494, 1263, 119, 28);

        streetname1TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetname1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetname1TextFieldActionPerformed(evt);
            }
        });
        add(streetname1TextField);
        streetname1TextField.setBounds(494, 1226, 119, 28);

        countryTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });
        add(countryTextField);
        countryTextField.setBounds(494, 1347, 119, 28);

        zipCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeTextFieldActionPerformed(evt);
            }
        });
        add(zipCodeTextField);
        zipCodeTextField.setBounds(494, 1391, 119, 28);

        firstNameTextField23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField23ActionPerformed(evt);
            }
        });
        add(firstNameTextField23);
        firstNameTextField23.setBounds(494, 1437, 119, 28);
        add(textArea1);
        textArea1.setBounds(490, 1100, 130, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void createResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResumeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createResumeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void emailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void computerSkillsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerSkillsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerSkillsTextFieldActionPerformed

    private void linkedINProfileLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedINProfileLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkedINProfileLinkTextFieldActionPerformed

    private void degreeTitle1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle1TextFieldActionPerformed

    private void degree1DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree1DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree1DateTextFieldActionPerformed

    private void university1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university1TextFieldActionPerformed

    private void degreeTitle2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle2TextFieldActionPerformed

    private void degree2DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree2DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree2DateTextFieldActionPerformed

    private void university2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university2TextFieldActionPerformed

    private void degreeTitle3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTitle3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeTitle3TextFieldActionPerformed

    private void degree3DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree3DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree3DateTextFieldActionPerformed

    private void university3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university3TextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void streetname2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetname2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetname2TextFieldActionPerformed

    private void streetname1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetname1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetname1TextFieldActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void firstNameTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressInformationLabel;
    private javax.swing.JLabel addressInformationLabel1;
    private javax.swing.JLabel careerObjectiveLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField computerSkillsTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createResumeButton;
    private javax.swing.JLabel createResumeTitleLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel degree1DateLabel;
    private javax.swing.JTextField degree1DateTextField;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JLabel degree1Label1;
    private javax.swing.JLabel degree1TitleLabel;
    private javax.swing.JLabel degree2DateLabel;
    private javax.swing.JTextField degree2DateTextField;
    private javax.swing.JLabel degree2TitleLabel;
    private javax.swing.JLabel degree3DateLabel;
    private javax.swing.JTextField degree3DateTextField;
    private javax.swing.JLabel degree3Label;
    private javax.swing.JLabel degree3TitleLabel;
    private javax.swing.JTextField degreeTitle1TextField;
    private javax.swing.JTextField degreeTitle2TextField;
    private javax.swing.JTextField degreeTitle3TextField;
    private javax.swing.JLabel educationHistoryLabel;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel emailAddressLabel1;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField firstNameTextField23;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JButton imageAttachButton;
    private javax.swing.JTextField imageURLTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField linkedINProfileLinkTextField;
    private javax.swing.JLabel linkedInProfileLinkLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel streetName1Label;
    private javax.swing.JLabel streetName2Label;
    private javax.swing.JTextField streetname1TextField;
    private javax.swing.JTextField streetname2TextField;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel university1Name;
    private javax.swing.JTextField university1TextField;
    private javax.swing.JLabel university2Name;
    private javax.swing.JTextField university2TextField;
    private javax.swing.JLabel university3Name;
    private javax.swing.JTextField university3TextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
